---
name: Check Lint

on:
  push:

jobs:
  lint:
    name: Check Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false
          VALIDATE_TERRAFORM_TFLINT: false
          VALIDATE_TERRAFORM_TERRASCAN: false
          VALIDATE_YAML: false
          # Disabling Terraform scans as we are using the Terragrunt scanner
